/*
 * David Cortinez
 * Module 3 - Lab 2
 * Purpose: The objective of this lab assignment is to provide you with a comprehensive hands-on experience in
 * object-oriented programming using Java. You will be creating multiple classes that interact with each other,
 * which will help you gain a deeper understanding of key object-oriented programming concepts. The specific skills
 *  you will be applying include creating classes, implementing encapsulation, and using constructors, with a
 * particular emphasis on copy constructors.
 */
/* ***Outline***
* Create the ParkingPermit class: This class will have the attributes: permitID, carMake, carModel, and carYear.

 1.1. permitID will be a random number between 1000 and 9999 generated by the program. This attribute should only have a getter method.The number will be genertated in the class.

 1.2. The carMake, carModel, and carYear attributes will be set by user input.

 1.3. Include a copy constructor in this class.

Create the Student class: This class will have the attributes: firstName, lastName, address, and parkingPermit.

 2.1. The firstName and lastName attributes will be set by user input.

 2.2. The address attribute will be an object of a class Address you created in Module 3, Lab 1.

 2.3. The parkingPermit attribute will be an object of the ParkingPermit class you just created.

Create the Header class: This class will contain a static method that displays a welcome message to the user. The Header class should be static and provide a message that outputs: “Welcome to the Alamo College Parking System”

Write your main program:

 4.1. First, use the Header class to display the welcome message.

 4.2. Use the Scanner class to collect user input for the student's first name, last name, home address, and car information (make, model, and year).

 4.3. Instantiate the ParkingPermit class with the car information provided by the user, and instantiate the Student class with the student information and the ParkingPermit object created in the previous step.

 4.4. Finally, output the student's information and parking permit details in a creative format. */


import java.util.Scanner;

public class Driver {
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);

        //Asking user to input info
        Header.displayHeader();
        System.out.println("Enter your first name: ");
        String fName = scan.nextLine();

        System.out.println("Enter your last name: ");
        String lName = scan.nextLine();

        System.out.println("Street: ");
        String street = scan.nextLine();

        System.out.println("City: ");
        String city = scan.nextLine();

        System.out.println("State: ");
        String state = scan.nextLine();

        System.out.println("Zip code: ");
        String zip = scan.nextLine();

        System.out.println("Enter your car make: ");
        String make = scan.nextLine();

        System.out.println("Enter your car model: ");
        String model = scan.nextLine();

        System.out.println("Enter your car year: ");
        String year = scan.nextLine();

        //Instantiating objects
        ParkingPermit parkingPermit = new ParkingPermit(make, model, year, new ParkingPermit());
        Address address = new Address(street, city, state, zip);
        Student student = new Student(fName, lName, address, parkingPermit);

        //Copy
        Address addressCopy = new Address(address);
        ParkingPermit parkingPermitCopy = new ParkingPermit(parkingPermit);

        //Output
        System.out.println("\n" + student.printStudentInfo() + "\n" + address.printAddress() + " " + parkingPermit.printPermit());

//        System.out.println("~~~~Copy of Address~~~~\n" + addressCopy.printAddress());
//        System.out.println("~~~~Copy of Parking Permit~~~~\n" + parkingPermitCopy.printPermit());
    }
}
